### ISSUE TITLE
add short description in repo

### ISSUE THREAD

**Issue by kubil-ismail** [nluthfis/fe-react_pijarfood#2]
Please add short description in your repo app

**Comment by kubil-ismail** [comment]
still empty
<img width="344" alt="Screenshot 2023-08-10 at 00 47 35" src="https://github.com/nluthfis/pijar_food_web/assets/49361887/dea49ee8-71b5-4061-9ebd-13ca127ea6cb">

**Comment by nluthfis** [comment]
![image](https://github.com/nluthfis/pijar_food_web/assets/42950482/3233a4b1-4c35-4463-8e35-c03496adcedf)
fixed!
